"""Export a verified agent graph as a production LangGraph repository.

The export is a complete repo, not a snippet: graph code, tool stubs, an
executable policy module, prompts, pytest suites generated from the simulation
scenarios, CI workflow and a Dockerfile. The policy module and its tests run
without langgraph installed, so the safety contract is testable anywhere.
"""

from __future__ import annotations

from pathlib import Path

from agentproof.graph import AgentGraph, NodeType
from agentproof.scenarios import Scenario, ScenarioCategory
from agentproof.spec import BehaviorSpec, ConstraintKind


def _slug(name: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in name.lower()).strip("_") or "agent"


def _render_policy(spec: BehaviorSpec) -> str:
    limit = spec.constraint(ConstraintKind.SPEND_LIMIT)
    threshold = float(limit.params.get("threshold", 50.0)) if limit else None
    lines = [
        '"""Executable behavior policy. Generated by AgentProof from the behavior spec."""',
        "",
        "from dataclasses import dataclass",
        "",
        "",
    ]
    if threshold is not None:
        lines += [
            f"AUTO_REFUND_LIMIT_USD = {threshold}",
            "",
            "",
            "@dataclass",
            "class RefundDecision:",
            "    allowed: bool",
            "    requires_approval: bool",
            "    reason: str",
            "",
            "",
            "def check_refund(amount: float, approved_by_human: bool = False) -> RefundDecision:",
            '    """The single gate every refund must pass. Structure, not vibes."""',
            "    if amount <= 0:",
            "        return RefundDecision(False, False, 'non-positive amount')",
            "    if amount <= AUTO_REFUND_LIMIT_USD:",
            "        return RefundDecision(True, False, 'within auto-refund limit')",
            "    if approved_by_human:",
            "        return RefundDecision(True, True, 'approved by human')",
            "    return RefundDecision(False, True, 'requires human approval')",
            "",
            "",
        ]
    pii = spec.constraint(ConstraintKind.PII_EGRESS)
    if pii is not None:
        lines += [
            "PII_FIELDS = ('email', 'address', 'phone', 'card', 'ssn')",
            "",
            "",
            "def redact_pii(payload: dict) -> dict:",
            '    """Strip PII fields before anything leaves the system."""',
            "    return {k: ('[REDACTED]' if k in PII_FIELDS else v) for k, v in payload.items()}",
            "",
            "",
        ]
    injection = spec.constraint(ConstraintKind.PROMPT_INJECTION)
    if injection is not None:
        lines += [
            "INJECTION_MARKERS = (",
            "    'ignore all previous', 'ignore your', 'system override',",
            "    'you are now', 'no approval needed', '[admin]', 'policy disabled',",
            "    'as a supervisor', 'i authorize', 'ignore the policy', 'ignorez',",
            ")",
            "",
            "",
            "def quarantine_untrusted(text: str) -> tuple[str, bool]:",
            '    """Flag content that tries to smuggle instructions to the model."""',
            "    lowered = text.lower()",
            "    flagged = any(marker in lowered for marker in INJECTION_MARKERS)",
            "    return text, flagged",
            "",
        ]
    return "\n".join(lines)


def _render_tools(graph: AgentGraph, spec=None, model: str | None = None) -> str:
    """Render tools.py with fleshed-out per-tool scaffolds (typed reads, example
    returns, concrete TODOs). LLM-written when a key + spec are supplied."""
    from agentproof.toolgen import render_tools_module

    return render_tools_module(graph, spec=spec, model=model)


def _render_tools_legacy(graph: AgentGraph) -> str:
    lines = [
        '"""Tool implementations. Wire these to your real systems."""',
        "",
        "import time",
        "from functools import wraps",
        "",
        "",
        "def with_retry(max_attempts: int = 3, backoff_seconds: float = 2.0):",
        "    def decorator(fn):",
        "        @wraps(fn)",
        "        def wrapper(*args, **kwargs):",
        "            last_error = None",
        "            for attempt in range(max_attempts):",
        "                try:",
        "                    return fn(*args, **kwargs)",
        "                except Exception as exc:  # noqa: BLE001 - retry boundary",
        "                    last_error = exc",
        "                    time.sleep(backoff_seconds * (attempt + 1))",
        "            raise last_error",
        "        return wrapper",
        "    return decorator",
        "",
        "",
    ]
    for node in graph.nodes_of_type(NodeType.TOOL):
        retry = node.config.get("retry")
        if retry:
            lines.append(
                f"@with_retry(max_attempts={retry.get('max_attempts', 3)}, "
                f"backoff_seconds={retry.get('backoff_seconds', 2)})"
            )
        lines += [
            f"def {node.id}(state: dict) -> dict:",
            f'    """{node.label}. Return a partial state update (only the keys',
            '    you change), e.g. {"customer": ...} — never the whole state."""',
            "    raise NotImplementedError('wire this tool to your real system')",
            "",
            "",
        ]
    return "\n".join(lines)


def _linear_spine(graph: AgentGraph) -> list[str]:
    """Canonical linear order for the runnable spine, by node role.

    A verified graph carries the agent-loop shape (tools return to the planner)
    plus fallback branches — cyclic and not directly runnable in LangGraph. We
    project it onto a predictable pipeline: input, injection guard, planner,
    lookup tools, the money gate + spend tool, other tools, responder, PII
    guard, egress tool, output. Guarantees input first and output last, so the
    emitted edges always form a valid acyclic graph. Fallbacks are omitted
    (the retry decorator covers resilience).
    """
    order: list[str] = []

    def add(node) -> None:
        if node is not None and node.id not in order:
            order.append(node.id)

    llms = graph.nodes_of_type(NodeType.LLM)
    planner = llms[0] if llms else None
    responder = next((n for n in llms if n is not planner), None)

    add(graph.find(lambda n: n.type == NodeType.INPUT))
    add(graph.find(lambda n: n.type == NodeType.GUARD and n.config.get("kind") == "injection_guard"))
    add(planner)
    for tool in graph.nodes_of_type(NodeType.TOOL):
        if tool.config.get("datasource") is not None:
            add(tool)
    add(graph.find(lambda n: n.type == NodeType.CONDITION))
    for tool in graph.nodes_of_type(NodeType.TOOL):
        if tool.config.get("spend"):
            add(tool)
    for tool in graph.nodes_of_type(NodeType.TOOL):
        if not tool.config.get("datasource") and not tool.config.get("spend") and not tool.config.get("external"):
            add(tool)
    add(responder)
    add(graph.find(lambda n: n.type == NodeType.GUARD and n.config.get("kind") == "pii_redaction"))
    for tool in graph.nodes_of_type(NodeType.TOOL):
        if tool.config.get("external"):
            add(tool)
    add(graph.find(lambda n: n.type == NodeType.OUTPUT))

    # Any remaining non-fallback nodes (e.g. approval, extra guards) go before output.
    out_id = order[-1] if order and graph.node(order[-1]).type == NodeType.OUTPUT else None
    for node in graph.nodes:
        if node.type == NodeType.FALLBACK or node.id in order:
            continue
        if out_id is not None:
            order.insert(order.index(out_id), node.id)
        else:
            order.append(node.id)
    return order


def _render_graph(graph: AgentGraph, spec: BehaviorSpec) -> str:
    limit = spec.constraint(ConstraintKind.SPEND_LIMIT)
    threshold = float(limit.params.get("threshold", 50.0)) if limit else 50.0
    lines = [
        '"""LangGraph assembly. Generated by AgentProof; structure mirrors the verified canvas."""',
        "",
        "import operator",
        "from typing import Annotated",
        "",
        "from langgraph.graph import END, START, StateGraph",
        "from typing_extensions import TypedDict",
        "",
        "from agent import policy, tools",
        "",
        "",
        "class AgentState(TypedDict, total=False):",
        "    # `messages` accumulates across parallel branches, so it needs a",
        "    # reducer; other keys are single-writer. Node functions return only",
        "    # the keys they change (partial updates), never the whole state.",
        "    messages: Annotated[list, operator.add]",
        "    amount: float",
        "    approved_by_human: bool",
        "    pii: dict",
        "    flagged: bool",
        "",
        "",
    ]
    condition = next(iter(graph.nodes_of_type(NodeType.CONDITION)), None)
    for node in graph.nodes:
        if node.type in (NodeType.INPUT, NodeType.OUTPUT, NodeType.CONDITION):
            continue
        if node.type == NodeType.TOOL:
            continue  # tool functions live in tools.py
        fn_name = node.id
        lines += [
            f"def {fn_name}(state: AgentState) -> dict:",
            f'    """{node.label}."""',
        ]
        if node.type == NodeType.GUARD and node.config.get("kind") == "pii_redaction":
            lines.append("    return {'pii': policy.redact_pii(state.get('pii', {}))}")
        elif node.type == NodeType.GUARD:
            lines.append(
                "    _, flagged = policy.quarantine_untrusted("
                "str((state.get('messages') or [''])[-1]))"
            )
            lines.append("    return {'flagged': flagged}")
        elif node.type == NodeType.APPROVAL:
            lines.append("    # Interrupt here and wait for a human decision.")
            lines.append("    return {'approved_by_human': bool(state.get('approved_by_human'))}")
        else:
            lines.append("    return {}")
        lines += ["", ""]

    lines += [
        "def build_graph() -> StateGraph:",
        "    graph = StateGraph(AgentState)",
    ]
    # A verified graph carries the agent-loop shape (tools return to the
    # planner) plus fallback branches. LangGraph needs an acyclic spine with
    # the money gate as a conditional branch, so we linearize here.
    spine = _linear_spine(graph)
    approval = next(iter(graph.nodes_of_type(NodeType.APPROVAL)), None)
    spend_tool = graph.find(lambda n: n.type == NodeType.TOOL and n.config.get("spend"))
    branch_nodes = {n.id for n in graph.nodes if n.type in (NodeType.CONDITION, NodeType.FALLBACK)}
    if approval is not None:
        branch_nodes.add(approval.id)

    for node_id in spine:
        node = graph.node(node_id)
        # INPUT/OUTPUT are START/END; CONDITION and APPROVAL are added below.
        if node.type in (NodeType.INPUT, NodeType.OUTPUT, NodeType.CONDITION, NodeType.APPROVAL):
            continue
        target = f"tools.{node.id}" if node.type == NodeType.TOOL else node.id
        lines.append(f"    graph.add_node('{node.id}', {target})")
    if condition is not None:
        lines.append(f"    graph.add_node('{condition.id}', lambda state: {{}})")
    if approval is not None:
        lines.append(f"    graph.add_node('{approval.id}', {approval.id})")

    if condition is not None and spend_tool is not None:
        lines += [
            "",
            "    def refund_gate(state: AgentState) -> str:",
            "        decision = policy.check_refund(state.get('amount', 0.0), state.get('approved_by_human', False))",
            "        if decision.allowed and not decision.requires_approval:",
            "            return 'auto'",
            "        return 'approval'",
            "",
        ]

    main = [nid for nid in spine if nid not in branch_nodes]
    for i in range(len(main) - 1):
        a, b = main[i], main[i + 1]
        a_node, b_node = graph.node(a), graph.node(b)
        src = "START" if a_node.type == NodeType.INPUT else f"'{a}'"
        # Route the money gate as a conditional branch just before the spend tool.
        if condition is not None and spend_tool is not None and b == spend_tool.id:
            lines.append(f"    graph.add_edge({src}, '{condition.id}')")
            approval_repr = f"'{approval.id}'" if approval is not None else f"'{spend_tool.id}'"
            lines.append(
                f"    graph.add_conditional_edges('{condition.id}', refund_gate, "
                f"{{'auto': '{spend_tool.id}', 'approval': {approval_repr}}})"
            )
            if approval is not None:
                lines.append(f"    graph.add_edge('{approval.id}', '{spend_tool.id}')")
            continue
        dst = "END" if b_node.type == NodeType.OUTPUT else f"'{b}'"
        lines.append(f"    graph.add_edge({src}, {dst})")
    lines += [
        "    return graph",
        "",
        "",
        "app = build_graph().compile()",
        "",
    ]
    return "\n".join(lines)


def _render_prompts(spec: BehaviorSpec) -> str:
    caps = "\n".join(f"- {c.description}" for c in spec.capabilities)
    rules = "\n".join(f"- {c.description}" for c in spec.constraints)
    return (
        '"""System prompts. The prompt states the contract; the graph enforces it."""\n'
        "\n"
        'SYSTEM_PROMPT = """You are a support agent.\n'
        "\n"
        "You can:\n"
        f"{caps}\n"
        "\n"
        "Hard rules (enforced by the system, do not attempt to bypass):\n"
        f"{rules}\n"
        '"""\n'
    )


def _render_policy_tests(spec: BehaviorSpec, scenarios: list[Scenario]) -> str:
    limit = spec.constraint(ConstraintKind.SPEND_LIMIT)
    threshold = float(limit.params.get("threshold", 50.0)) if limit else 50.0
    lines = [
        '"""Behavior tests generated by AgentProof from the simulation suite."""',
        "",
        "from agent import policy",
        "",
        "",
        "def test_auto_refund_within_limit():",
        f"    decision = policy.check_refund({threshold} - 0.01)",
        "    assert decision.allowed and not decision.requires_approval",
        "",
        "",
        "def test_refund_at_exact_limit_is_automatic():",
        f"    decision = policy.check_refund({threshold})",
        "    assert decision.allowed and not decision.requires_approval",
        "",
        "",
        "def test_refund_above_limit_requires_approval():",
        f"    decision = policy.check_refund({threshold} + 0.01)",
        "    assert not decision.allowed and decision.requires_approval",
        "",
        "",
        "def test_refund_above_limit_with_approval_is_allowed():",
        f"    decision = policy.check_refund({threshold} * 2, approved_by_human=True)",
        "    assert decision.allowed",
        "",
        "",
        "def test_zero_and_negative_amounts_rejected():",
        "    assert not policy.check_refund(0).allowed",
        "    assert not policy.check_refund(-5).allowed",
        "",
    ]
    if spec.constraint(ConstraintKind.PII_EGRESS):
        lines += [
            "",
            "def test_pii_is_redacted_before_egress():",
            "    payload = {'email': 'a@b.com', 'order': '123', 'card': '4242'}",
            "    redacted = policy.redact_pii(payload)",
            "    assert redacted['email'] == '[REDACTED]'",
            "    assert redacted['card'] == '[REDACTED]'",
            "    assert redacted['order'] == '123'",
            "",
        ]
    if spec.constraint(ConstraintKind.PROMPT_INJECTION):
        payloads = [
            s.user_message
            for s in scenarios
            if s.category == ScenarioCategory.PROMPT_INJECTION
        ][:3]
        lines += ["", "def test_injection_payloads_are_flagged():"]
        for payload in payloads:
            escaped = payload.replace("\\", "\\\\").replace("'", "\\'")
            lines.append(f"    assert policy.quarantine_untrusted('{escaped}')[1]")
        lines.append("")
    return "\n".join(lines)


def _render_ci() -> str:
    return (
        "name: agent-ci\n"
        "on:\n"
        "  push:\n"
        "  pull_request:\n"
        "jobs:\n"
        "  behavior-tests:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-python@v5\n"
        "        with:\n"
        "          python-version: '3.11'\n"
        "      - run: pip install pytest\n"
        "      - name: Behavior tests (policy contract)\n"
        "        run: pytest tests/ -v\n"
    )


def _render_dockerfile() -> str:
    return (
        "FROM python:3.11-slim\n"
        "WORKDIR /app\n"
        "COPY requirements.txt .\n"
        "RUN pip install --no-cache-dir -r requirements.txt\n"
        "COPY . .\n"
        'CMD ["python", "-m", "agent.graph"]\n'
    )


def _render_readme(spec: BehaviorSpec, graph: AgentGraph) -> str:
    tools = ", ".join(n.id for n in graph.nodes_of_type(NodeType.TOOL))
    guards = ", ".join(
        n.id for n in graph.nodes if n.type in (NodeType.GUARD, NodeType.APPROVAL)
    )
    return (
        f"# {spec.name}\n\n"
        "Generated by [AgentProof](https://github.com/evanl666/agentproof) — "
        "this agent's structure was verified by simulation before export.\n\n"
        f"- Tools: {tools or 'none'}\n"
        f"- Enforcement: {guards or 'none'}\n\n"
        "## Run the behavior tests\n\n"
        "```bash\n"
        "pip install pytest\n"
        "pytest tests/ -v\n"
        "```\n\n"
        "## Run the agent\n\n"
        "```bash\n"
        "pip install -r requirements.txt\n"
        "python -c 'from agent.graph import app; print(app)'\n"
        "```\n"
    )


def export_langgraph(
    spec: BehaviorSpec,
    graph: AgentGraph,
    scenarios: list[Scenario],
    out_dir: str | Path,
) -> list[Path]:
    """Write the full production repo. Returns the list of files written."""
    out = Path(out_dir)
    files = {
        "agent/__init__.py": "",
        "agent/graph.py": _render_graph(graph, spec),
        "agent/tools.py": _render_tools(graph),
        "agent/policy.py": _render_policy(spec),
        "agent/prompts.py": _render_prompts(spec),
        "tests/__init__.py": "",
        "tests/test_policy.py": _render_policy_tests(spec, scenarios),
        ".github/workflows/ci.yml": _render_ci(),
        "Dockerfile": _render_dockerfile(),
        "requirements.txt": "langgraph>=0.2\ntyping-extensions\n",
        "README.md": _render_readme(spec, graph),
    }
    written: list[Path] = []
    for rel_path, content in files.items():
        path = out / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        written.append(path)
    return written
