"""Flexible, framework-agnostic export — target *any* framework, not a hardcoded list.

Writing a bespoke exporter per framework doesn't scale and locks users to whatever
we happened to hardcode. Instead: the verified *policy contract* is generated
deterministically (it must be exactly correct — it's the safety core, and its
tests run standalone), while the framework-specific *assembly* — how this
framework declares tools and constructs an agent — is written by a model from the
verified graph. Name any framework ("langchain", "autogen", "pydantic-ai",
"agno", "google-adk", or one nobody has integrated yet) and you get a runnable
repo whose guards are enforced inside the tools.

Deterministic templates still handle the common frameworks offline; the LLM path
generalizes to everything else and is the default when a key is present.
"""

from __future__ import annotations

from pathlib import Path

from agentproof.export.langgraph import (
    _render_policy,
    _render_policy_tests,
    _render_prompts,
    _render_tools,
)
from agentproof.graph import AgentGraph, NodeType
from agentproof.scenarios import Scenario
from agentproof.spec import BehaviorSpec, ConstraintKind, coerce_threshold


def _tool_manifest(graph: AgentGraph) -> list[dict]:
    """A compact, framework-neutral description of the verified tools + risk."""
    out = []
    for n in graph.nodes_of_type(NodeType.TOOL):
        out.append({
            "id": n.id,
            "label": n.label,
            "high_risk": bool(n.config.get("high_risk") or n.config.get("spend")),
            "moves_money": bool(n.config.get("spend")),
            "external": bool(n.config.get("external")),
            "reads_sensitive": bool(n.config.get("returns_pii") or n.config.get("sensitive")),
        })
    return out


_ASSEMBLY_SYSTEM = """You generate the agent-assembly file for a specific AI-agent
framework, wiring a set of verified tools into a runnable agent. A separate
`policy.py` module already exists in the same package and exposes the safety
contract — at minimum `check_refund(amount, approved_by_human=False)` returning
an object with `.allowed`, plus (if present) `redact_pii(payload)` and
`quarantine_untrusted(text)`. Requirements:

- Import the policy: `from agent import policy` (and `from agent import tools` for
  the raw tool stubs).
- Declare each tool the target framework's idiomatic way.
- Inside every MONEY-MOVING or HIGH-RISK tool, call the policy gate FIRST and
  refuse if it doesn't allow the action.
- Construct the agent/assistant with all tools and a system prompt.
- Output ONLY the code for `agent.py` — no markdown fences, no prose."""


def _llm_assembly(spec: BehaviorSpec, graph: AgentGraph, framework: str, model: str) -> str:
    import anthropic

    manifest = _tool_manifest(graph)
    limit = spec.constraint(ConstraintKind.SPEND_LIMIT)
    threshold = coerce_threshold(limit.params.get("threshold")) if limit else None
    ctx = (
        f"Target framework: {framework}\n"
        f"Agent name: {spec.name}\n"
        f"Spend policy limit: {threshold}\n"
        f"Tools (id, flags):\n"
        + "\n".join(
            f"- {t['id']} ({t['label']}): "
            f"{'MONEY ' if t['moves_money'] else ''}"
            f"{'HIGH_RISK ' if t['high_risk'] and not t['moves_money'] else ''}"
            f"{'EXTERNAL ' if t['external'] else ''}"
            f"{'SENSITIVE' if t['reads_sensitive'] else ''}"
            for t in manifest
        )
        + f"\n\nGenerate agent.py for {framework}."
    )
    resp = anthropic.Anthropic().messages.create(
        model=model, max_tokens=2000, system=_ASSEMBLY_SYSTEM,
        messages=[{"role": "user", "content": ctx}],
    )
    text = next((b.text for b in resp.content if b.type == "text"), "")
    # Strip accidental code fences.
    if "```" in text:
        parts = text.split("```")
        text = max(parts, key=len)
        if text.lstrip().startswith(("python", "py")):
            text = text.split("\n", 1)[1] if "\n" in text else text
    return text.strip() + "\n"


def _fallback_assembly(spec: BehaviorSpec, graph: AgentGraph, framework: str) -> str:
    """A generic, framework-neutral assembly used offline for unknown frameworks.

    It's plain Python that enforces the policy gate around each guarded tool, with
    a comment pointing at where to plug the framework's agent constructor."""
    tools = _tool_manifest(graph)
    lines = [
        f'"""{spec.name} — {framework} assembly (generated by AgentProof).',
        "",
        f"AgentProof could not reach a model to write idiomatic {framework} code, so",
        "this is a framework-neutral scaffold: each guarded tool enforces the policy",
        f"contract. Adapt the agent constructor at the bottom to {framework}.",
        '"""',
        "",
        "from agent import policy, tools",
        "from agent.prompts import SYSTEM_PROMPT",
        "",
        "",
    ]
    tool_ids = []
    for t in tools:
        tool_ids.append(t["id"])
        if t["moves_money"]:
            lines += [
                f"def {t['id']}(amount, approved_by_human=False):",
                f'    """{t["label"]} — policy-gated."""',
                "    decision = policy.check_refund(amount, approved_by_human)",
                "    if not decision.allowed:",
                "        return f'BLOCKED by policy: {decision.reason}'",
                f"    return tools.{t['id']}({{'amount': amount}})",
                "", "",
            ]
        else:
            lines += [
                f"def {t['id']}(**kwargs):",
                f'    """{t["label"]}."""',
                f"    return tools.{t['id']}(kwargs)",
                "", "",
            ]
    lines += [
        f"# TODO: construct your {framework} agent with these tools and SYSTEM_PROMPT:",
        f"TOOLS = [{', '.join(tool_ids)}]",
        "",
    ]
    return "\n".join(lines)


def export_framework(
    framework: str,
    spec: BehaviorSpec,
    graph: AgentGraph,
    scenarios: list[Scenario],
    out_dir: str | Path,
    model: str | None = None,
) -> list[Path]:
    """Export a verified agent to ANY framework by name (LLM-assembled + tested policy)."""
    from agentproof.intelligence import use_llm

    out = Path(out_dir)
    if use_llm(model):
        try:
            assembly = _llm_assembly(spec, graph, framework, model or "claude-haiku-4-5")
        except Exception:  # noqa: BLE001
            assembly = _fallback_assembly(spec, graph, framework)
    else:
        assembly = _fallback_assembly(spec, graph, framework)

    files = {
        "agent/__init__.py": "",
        "agent/agent.py": assembly,
        "agent/tools.py": _render_tools(graph, spec=spec, model=model),
        "agent/policy.py": _render_policy(spec),
        "agent/prompts.py": _render_prompts(spec),
        "tests/__init__.py": "",
        "tests/test_policy.py": _render_policy_tests(spec, scenarios),
        "requirements.txt": f"# add your {framework} dependency here\n",
        "README.md": (
            f"# {spec.name} ({framework})\n\n"
            "Generated by AgentProof. The safety contract in `agent/policy.py` is "
            "verified and tested standalone (`pytest tests/`); `agent/agent.py` wires "
            f"it into {framework}.\n"
        ),
    }
    written: list[Path] = []
    for rel, content in files.items():
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
        written.append(p)
    return written
