"""Additional export targets: OpenAI Agents SDK, CrewAI, and TypeScript.

Developers shouldn't be locked into one framework to get AgentProof's
guarantees. Each target emits a runnable repo whose *policy contract* — the
verified core — is executable and tested standalone, with framework-specific
assembly wired on top. The Python targets reuse the same generated `policy.py`
(so the safety contract is identical across frameworks); the TypeScript target
emits an equivalent `policy.ts` plus a dependency-free test.
"""

from __future__ import annotations

from pathlib import Path

from agentproof.export.langgraph import (
    _render_policy,
    _render_policy_tests,
    _render_prompts,
    _render_tools,
)
from agentproof.graph import AgentGraph, NodeType
from agentproof.scenarios import Scenario, ScenarioCategory
from agentproof.spec import BehaviorSpec, ConstraintKind


def _write(out: Path, files: dict[str, str]) -> list[Path]:
    written: list[Path] = []
    for rel, content in files.items():
        path = out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        written.append(path)
    return written


# ---------------------------------------------------------------------------
# OpenAI Agents SDK (Python)
# ---------------------------------------------------------------------------

def _render_openai_agent(spec: BehaviorSpec, graph: AgentGraph) -> str:
    tools = graph.nodes_of_type(NodeType.TOOL)
    limit = spec.constraint(ConstraintKind.SPEND_LIMIT)
    threshold = float(limit.params.get("threshold", 50.0)) if limit else 50.0
    tool_defs = []
    for t in tools:
        guarded = t.config.get("spend")
        body = (
            f"    decision = policy.check_refund(amount)\n"
            f"    if not decision.allowed:\n"
            f"        return f'BLOCKED by policy: {{decision.reason}}'\n"
            f"    return tools.{t.id}({{'amount': amount}})"
            if guarded
            else f"    return tools.{t.id}({{}})"
        )
        sig = "amount: float" if guarded else ""
        tool_defs.append(
            f"@function_tool\n"
            f"def {t.id}({sig}) -> str:\n"
            f'    """{t.label}."""\n'
            f"{body}\n"
        )
    tools_block = "\n\n".join(tool_defs)
    return (
        '"""OpenAI Agents SDK assembly. Generated by AgentProof.\n\n'
        "The policy gate is enforced *inside* each guarded tool, so the safety\n"
        "contract holds regardless of what the model decides to call.\n"
        '"""\n\n'
        "from agents import Agent, function_tool\n\n"
        "from agent import policy, tools\n"
        "from agent.prompts import SYSTEM_PROMPT\n\n\n"
        f"{tools_block}\n\n"
        "agent = Agent(\n"
        '    name="' + spec.name + '",\n'
        "    instructions=SYSTEM_PROMPT,\n"
        f"    model='claude-sonnet-5',\n"
        "    tools=[" + ", ".join(t.id for t in tools) + "],\n"
        ")\n"
    )


def export_openai_agents(
    spec: BehaviorSpec, graph: AgentGraph, scenarios: list[Scenario], out_dir: str | Path
) -> list[Path]:
    out = Path(out_dir)
    files = {
        "agent/__init__.py": "",
        "agent/agent.py": _render_openai_agent(spec, graph),
        "agent/tools.py": _render_tools(graph),
        "agent/policy.py": _render_policy(spec),
        "agent/prompts.py": _render_prompts(spec),
        "tests/__init__.py": "",
        "tests/test_policy.py": _render_policy_tests(spec, scenarios),
        "requirements.txt": "openai-agents>=0.1\n",
        "README.md": _readme(spec, "OpenAI Agents SDK", "python -m agent.agent"),
        ".github/workflows/ci.yml": _py_ci(),
        "Dockerfile": _py_dockerfile("agent.agent"),
    }
    return _write(out, files)


# ---------------------------------------------------------------------------
# CrewAI (Python)
# ---------------------------------------------------------------------------

def _render_crewai(spec: BehaviorSpec, graph: AgentGraph) -> str:
    tools = graph.nodes_of_type(NodeType.TOOL)
    tool_defs = []
    for t in tools:
        guarded = t.config.get("spend")
        if guarded:
            run = (
                "        decision = policy.check_refund(float(amount))\n"
                "        if not decision.allowed:\n"
                "            return f'BLOCKED by policy: {decision.reason}'\n"
                "        return tools.%s({'amount': float(amount)})" % t.id
            )
            args = "self, amount: str"
        else:
            run = f"        return tools.{t.id}({{}})"
            args = "self"
        cls = "".join(p.capitalize() for p in t.id.split("_")) + "Tool"
        tool_defs.append(
            f"class {cls}(BaseTool):\n"
            f'    name: str = "{t.id}"\n'
            f'    description: str = "{t.label}"\n\n'
            f"    def _run({args}) -> str:\n"
            f"{run}\n"
        )
    tools_block = "\n\n".join(tool_defs)
    tool_instances = ", ".join(
        "".join(p.capitalize() for p in t.id.split("_")) + "Tool()" for t in tools
    )
    return (
        '"""CrewAI assembly. Generated by AgentProof.\n\n'
        "Each tool enforces the policy contract before acting, so an over-limit\n"
        "or injected request is blocked at the tool boundary.\n"
        '"""\n\n'
        "from crewai import Agent, Crew, Task\n"
        "from crewai.tools import BaseTool\n\n"
        "from agent import policy, tools\n"
        "from agent.prompts import SYSTEM_PROMPT\n\n\n"
        f"{tools_block}\n\n"
        "support_agent = Agent(\n"
        f'    role="{spec.name}",\n'
        '    goal="Resolve requests within the behavior contract.",\n'
        "    backstory=SYSTEM_PROMPT,\n"
        f"    tools=[{tool_instances}],\n"
        "    llm='claude-sonnet-5',\n"
        ")\n"
    )


def export_crewai(
    spec: BehaviorSpec, graph: AgentGraph, scenarios: list[Scenario], out_dir: str | Path
) -> list[Path]:
    out = Path(out_dir)
    files = {
        "agent/__init__.py": "",
        "agent/crew.py": _render_crewai(spec, graph),
        "agent/tools.py": _render_tools(graph),
        "agent/policy.py": _render_policy(spec),
        "agent/prompts.py": _render_prompts(spec),
        "tests/__init__.py": "",
        "tests/test_policy.py": _render_policy_tests(spec, scenarios),
        "requirements.txt": "crewai>=0.80\n",
        "README.md": _readme(spec, "CrewAI", "python -m agent.crew"),
        ".github/workflows/ci.yml": _py_ci(),
        "Dockerfile": _py_dockerfile("agent.crew"),
    }
    return _write(out, files)


# ---------------------------------------------------------------------------
# TypeScript (framework-neutral)
# ---------------------------------------------------------------------------

def _render_policy_ts(spec: BehaviorSpec) -> str:
    limit = spec.constraint(ConstraintKind.SPEND_LIMIT)
    threshold = float(limit.params.get("threshold", 50.0)) if limit else 50.0
    lines = [
        "// Executable behavior policy. Generated by AgentProof from the behavior spec.",
        "",
        f"export const AUTO_REFUND_LIMIT_USD = {threshold};",
        "",
        "export interface RefundDecision {",
        "  allowed: boolean;",
        "  requiresApproval: boolean;",
        "  reason: string;",
        "}",
        "",
        "export function checkRefund(amount: number, approvedByHuman = false): RefundDecision {",
        "  if (amount <= 0) return { allowed: false, requiresApproval: false, reason: 'non-positive amount' };",
        "  if (amount <= AUTO_REFUND_LIMIT_USD)",
        "    return { allowed: true, requiresApproval: false, reason: 'within auto-refund limit' };",
        "  if (approvedByHuman) return { allowed: true, requiresApproval: true, reason: 'approved by human' };",
        "  return { allowed: false, requiresApproval: true, reason: 'requires human approval' };",
        "}",
        "",
    ]
    if spec.constraint(ConstraintKind.PII_EGRESS):
        lines += [
            "export const PII_FIELDS = ['email', 'address', 'phone', 'card', 'ssn'];",
            "",
            "export function redactPii(payload: Record<string, unknown>): Record<string, unknown> {",
            "  const out: Record<string, unknown> = {};",
            "  for (const [k, v] of Object.entries(payload)) out[k] = PII_FIELDS.includes(k) ? '[REDACTED]' : v;",
            "  return out;",
            "}",
            "",
        ]
    if spec.constraint(ConstraintKind.PROMPT_INJECTION):
        lines += [
            "export const INJECTION_MARKERS = [",
            "  'ignore all previous', 'ignore your', 'system override', 'you are now',",
            "  'no approval needed', '[admin]', 'policy disabled', 'as a supervisor', 'i authorize',",
            "];",
            "",
            "export function quarantineUntrusted(text: string): { text: string; flagged: boolean } {",
            "  const lowered = text.toLowerCase();",
            "  const flagged = INJECTION_MARKERS.some((m) => lowered.includes(m));",
            "  return { text, flagged };",
            "}",
            "",
        ]
    return "\n".join(lines)


def _render_policy_test_ts(spec: BehaviorSpec, scenarios: list[Scenario]) -> str:
    limit = spec.constraint(ConstraintKind.SPEND_LIMIT)
    threshold = float(limit.params.get("threshold", 50.0)) if limit else 50.0
    extra_imports = []
    if spec.constraint(ConstraintKind.PII_EGRESS):
        extra_imports.append("redactPii")
    if spec.constraint(ConstraintKind.PROMPT_INJECTION):
        extra_imports.append("quarantineUntrusted")
    imports = "checkRefund" + ("".join(f", {n}" for n in extra_imports))
    lines = [
        "// Behavior tests generated by AgentProof. Runs on plain Node (node --test).",
        "import { test } from 'node:test';",
        "import assert from 'node:assert';",
        f"import {{ {imports} }} from '../agent/policy.ts';",
        "",
        "test('auto refund within limit', () => {",
        f"  const d = checkRefund({threshold} - 0.01);",
        "  assert.ok(d.allowed && !d.requiresApproval);",
        "});",
        "",
        "test('refund above limit requires approval', () => {",
        f"  const d = checkRefund({threshold} + 0.01);",
        "  assert.ok(!d.allowed && d.requiresApproval);",
        "});",
        "",
        "test('approved over-limit refund allowed', () => {",
        f"  assert.ok(checkRefund({threshold} * 2, true).allowed);",
        "});",
        "",
        "test('non-positive amounts rejected', () => {",
        "  assert.ok(!checkRefund(0).allowed);",
        "  assert.ok(!checkRefund(-5).allowed);",
        "});",
        "",
    ]
    if spec.constraint(ConstraintKind.PII_EGRESS):
        lines += [
            "test('PII redacted before egress', () => {",
            "  const r = redactPii({ email: 'a@b.com', order: '1', card: '4242' });",
            "  assert.strictEqual(r.email, '[REDACTED]');",
            "  assert.strictEqual(r.card, '[REDACTED]');",
            "  assert.strictEqual(r.order, '1');",
            "});",
            "",
        ]
    if spec.constraint(ConstraintKind.PROMPT_INJECTION):
        payloads = [
            s.user_message
            for s in scenarios
            if s.category == ScenarioCategory.PROMPT_INJECTION
        ][:3]
        lines.append("test('injection payloads flagged', () => {")
        for p in payloads:
            esc = p.replace("\\", "\\\\").replace("'", "\\'")
            lines.append(f"  assert.ok(quarantineUntrusted('{esc}').flagged);")
        lines += ["  assert.ok(!quarantineUntrusted('where is my order?').flagged);", "});", ""]
    return "\n".join(lines)


def _render_agent_ts(spec: BehaviorSpec, graph: AgentGraph) -> str:
    return (
        "// Framework-neutral agent entrypoint. Generated by AgentProof.\n"
        "// Wire your LLM client of choice here; the policy gate is enforced below.\n"
        "import { checkRefund } from './policy.ts';\n\n"
        "export function handleRefundRequest(amount: number, approvedByHuman = false): string {\n"
        "  const decision = checkRefund(amount, approvedByHuman);\n"
        "  if (!decision.allowed) return `BLOCKED by policy: ${decision.reason}`;\n"
        "  // ... call your refund tool here ...\n"
        "  return `refund of $${amount} processed`;\n"
        "}\n"
    )


def export_typescript(
    spec: BehaviorSpec, graph: AgentGraph, scenarios: list[Scenario], out_dir: str | Path
) -> list[Path]:
    out = Path(out_dir)
    files = {
        "agent/policy.ts": _render_policy_ts(spec),
        "agent/agent.ts": _render_agent_ts(spec, graph),
        "tests/policy.test.ts": _render_policy_test_ts(spec, scenarios),
        "package.json": (
            "{\n"
            f'  "name": "{_npm_slug(spec.name)}",\n'
            '  "version": "0.1.0",\n'
            '  "type": "module",\n'
            '  "scripts": { "test": "node --test --experimental-strip-types \\"tests/*.test.ts\\"" }\n'
            "}\n"
        ),
        "README.md": _readme(spec, "TypeScript", "npm test"),
        ".github/workflows/ci.yml": _ts_ci(),
    }
    return _write(out, files)


# ---------------------------------------------------------------------------
# shared helpers
# ---------------------------------------------------------------------------

def _npm_slug(name: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in name.lower()).strip("-") or "agent"


def _readme(spec: BehaviorSpec, framework: str, run_cmd: str) -> str:
    return (
        f"# {spec.name} ({framework})\n\n"
        "Generated by [AgentProof](https://github.com/evanl666/agentproof) — "
        "structure verified by simulation before export.\n\n"
        f"```bash\n{run_cmd}\n```\n"
    )


def _py_ci() -> str:
    return (
        "name: agent-ci\non:\n  push:\n  pull_request:\n"
        "jobs:\n  behavior-tests:\n    runs-on: ubuntu-latest\n    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-python@v5\n        with:\n          python-version: '3.11'\n"
        "      - run: pip install pytest\n"
        "      - run: pytest tests/ -v\n"
    )


def _ts_ci() -> str:
    return (
        "name: agent-ci\non:\n  push:\n  pull_request:\n"
        "jobs:\n  behavior-tests:\n    runs-on: ubuntu-latest\n    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "      - uses: actions/setup-node@v4\n        with:\n          node-version: '22'\n"
        "      - run: npm test\n"
    )


def _py_dockerfile(module: str) -> str:
    return (
        "FROM python:3.11-slim\nWORKDIR /app\n"
        "COPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n"
        f"COPY . .\nCMD [\"python\", \"-m\", \"{module}\"]\n"
    )


TARGETS = {
    "langgraph": None,  # handled by export.langgraph.export_langgraph
    "openai": export_openai_agents,
    "crewai": export_crewai,
    "typescript": export_typescript,
}
