"""Spec-to-compliance report — the artifact security & legal actually ask for.

Engineers care about the score; a security reviewer or an auditor wants a
controls document: what rules the agent is held to, how each is tested and
proven, which data-flows are governed, where approvals sit, and what gaps remain.
This renders exactly that from the verified project — as Markdown or a
self-contained HTML page you can attach to a SOC2/vendor-review packet.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from agentproof.coverage import compute_coverage
from agentproof.coverage2 import compute_risk_coverage
from agentproof.graph import AgentGraph, NodeType
from agentproof.proofs import prove
from agentproof.scenarios import Scenario
from agentproof.score import compute_score
from agentproof.simulator import run_suite
from agentproof.spec import BehaviorSpec


def compliance_data(spec: BehaviorSpec, graph: AgentGraph, scenarios: list[Scenario]) -> dict[str, Any]:
    results = run_suite(graph, spec, scenarios)
    coverage = compute_coverage(graph, results)
    risk_cov = compute_risk_coverage(graph, results)
    score = compute_score(results, coverage)
    proofs = prove(graph, spec)
    by_kind: dict[str, dict] = {}
    for r in results:
        cat = r.scenario.category.value
        by_kind.setdefault(cat, {"total": 0, "passed": 0})
        by_kind[cat]["total"] += 1
        by_kind[cat]["passed"] += int(r.passed)

    approvals = [n.id for n in graph.nodes_of_type(NodeType.APPROVAL)]
    sources = [n.id for n in graph.nodes if n.config.get("returns_pii") or n.config.get("sensitive")]
    sinks = [n.id for n in graph.nodes if n.config.get("external")]

    return {
        "name": spec.name,
        "controls": [c.to_dict() for c in spec.constraints],
        "capabilities": [c.description for c in spec.capabilities],
        "tests_by_category": by_kind,
        "proofs": [p.to_dict() for p in proofs],
        "score": score.to_dict(),
        "coverage": coverage.to_dict(),
        "risk_coverage": risk_cov.to_dict(),
        "approval_gates": approvals,
        "data_flows": {"sensitive_sources": sources, "external_sinks": sinks},
        "gaps": {
            "uncovered_high_risk_tools": risk_cov.uncovered_high_risk_tools,
            "open_proofs": [p.property for p in proofs if not p.holds],
        },
    }


def render_markdown(data: dict[str, Any]) -> str:
    s = data["score"]
    lines = [
        f"# Compliance report — {data['name']}",
        "",
        f"**Agent Score:** {s['overall']}/100 · "
        f"**Verdict:** {'SHIPPABLE' if s['shippable'] else 'NOT SHIPPABLE'} · "
        f"**Safety proofs:** {sum(p['holds'] for p in data['proofs'])}/{len(data['proofs'])} holding",
        "",
        "## Controls (behavior constraints)",
        "| Control | Type |",
        "|---|---|",
    ]
    lines += [f"| {c['description']} | `{c['kind']}` |" for c in data["controls"]]
    lines += ["", "## Test coverage by attack class", "| Class | Passed |", "|---|---|"]
    for cat, v in data["tests_by_category"].items():
        lines.append(f"| {cat} | {v['passed']}/{v['total']} |")
    lines += ["", "## Formal safety proofs", "| Property | Status |", "|---|---|"]
    for p in data["proofs"]:
        lines.append(f"| {p['property']} | {'✅ proven' if p['holds'] else '❌ VIOLATED'} |")
    lines += ["", "## Governed data-flows",
              f"- Sensitive sources: {', '.join(data['data_flows']['sensitive_sources']) or 'none'}",
              f"- External sinks: {', '.join(data['data_flows']['external_sinks']) or 'none'}",
              f"- Approval gates: {', '.join(data['approval_gates']) or 'none'}",
              "", "## Risk coverage",
              f"- High-risk tools tested by attacks: {round(data['risk_coverage']['high_risk_tool_coverage']*100)}%",
              f"- Sensitive→external data-flows exercised: {round(data['risk_coverage']['data_flow_coverage']*100)}%"]
    gaps = data["gaps"]
    lines += ["", "## Known gaps"]
    if gaps["open_proofs"] or gaps["uncovered_high_risk_tools"]:
        for p in gaps["open_proofs"]:
            lines.append(f"- ⚠️ Unproven: {p}")
        for t in gaps["uncovered_high_risk_tools"]:
            lines.append(f"- ⚠️ High-risk tool not attacked in tests: `{t}`")
    else:
        lines.append("- None — all controls tested, all safety properties proven.")
    lines += ["", "_Generated by AgentProof._"]
    return "\n".join(lines) + "\n"


def render_html(data: dict[str, Any]) -> str:
    import html as _html
    md = render_markdown(data)
    body = _html.escape(md)
    return (
        "<!DOCTYPE html><html><head><meta charset='utf-8'>"
        f"<title>Compliance — {_html.escape(data['name'])}</title>"
        "<style>body{font:14px/1.6 -apple-system,Segoe UI,sans-serif;max-width:820px;"
        "margin:40px auto;padding:0 20px;color:#1a1a1a}pre{white-space:pre-wrap}</style></head>"
        f"<body><pre>{body}</pre></body></html>"
    )


def write_compliance(path: str | Path, spec: BehaviorSpec, graph: AgentGraph,
                     scenarios: list[Scenario], fmt: str = "md") -> Path:
    data = compliance_data(spec, graph, scenarios)
    path = Path(path)
    path.write_text(render_html(data) if fmt == "html" else render_markdown(data))
    return path
