"""OpenAPI → safe agent tools compiler.

Most agents wire raw API calls straight into the model's hands — a `POST
/refunds` becomes a tool the model can fire at will. This compiler takes an
OpenAPI spec and generates *safe* tools instead: mutating operations get a
preview/commit split, an idempotency key, an undo where possible, and a
human-approval gate; read operations pass through. It also emits policy tests
and an MCP server stub. AgentProof stops being only a test tool and becomes a
generator of safe agent tools.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

_MUTATING = {"post", "put", "patch", "delete"}
_MONEY_HINTS = ("refund", "charge", "payment", "transfer", "payout", "invoice", "wire")
_DELETE_HINTS = ("delete", "remove", "revoke", "cancel")


@dataclass
class SafeTool:
    name: str
    method: str
    path: str
    summary: str
    mutating: bool
    high_risk: bool  # money movement or destructive
    needs_approval: bool
    idempotent: bool
    undoable: bool

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name, "method": self.method, "path": self.path,
            "summary": self.summary, "mutating": self.mutating, "high_risk": self.high_risk,
            "needs_approval": self.needs_approval, "idempotent": self.idempotent, "undoable": self.undoable,
        }


def _tool_name(method: str, path: str, op: dict) -> str:
    if op.get("operationId"):
        return re.sub(r"[^a-z0-9_]", "_", op["operationId"].lower()).strip("_")
    parts = [p for p in re.split(r"[/{}]", path) if p and not p.startswith(":")]
    return re.sub(r"[^a-z0-9_]+", "_", (method + "_" + "_".join(parts)).lower()).strip("_")


def compile_openapi(spec: dict[str, Any]) -> list[SafeTool]:
    """Turn an OpenAPI paths object into a list of safe tool descriptors."""
    tools: list[SafeTool] = []
    for path, methods in (spec.get("paths") or {}).items():
        if not isinstance(methods, dict):
            continue
        for method, op in methods.items():
            if method.lower() not in ({"get", "head", "options"} | _MUTATING):
                continue
            if not isinstance(op, dict):
                continue
            method_l = method.lower()
            mutating = method_l in _MUTATING
            text = f"{path} {op.get('summary', '')} {op.get('operationId', '')}".lower()
            money = any(h in text for h in _MONEY_HINTS)
            destructive = method_l == "delete" or any(h in text for h in _DELETE_HINTS)
            high_risk = money or destructive
            tools.append(SafeTool(
                name=_tool_name(method_l, path, op),
                method=method_l.upper(),
                path=path,
                summary=op.get("summary", "") or op.get("description", "") or f"{method_l} {path}",
                mutating=mutating,
                high_risk=high_risk,
                needs_approval=high_risk,
                idempotent=mutating,             # generated wrappers enforce idempotency keys
                undoable=mutating and not destructive,
            ))
    return tools


def render_tools_module(tools: list[SafeTool]) -> str:
    lines = [
        '"""Safe agent tools generated by AgentProof from an OpenAPI spec.',
        "",
        "Every mutating call is split into preview()/commit(); high-risk calls",
        "(money movement, deletion) require an approval token; commits carry an",
        'idempotency key so retries do not double-charge."""',
        "import uuid",
        "",
        "",
        "class ApprovalRequired(Exception):",
        "    pass",
        "",
        "",
        "def _idempotency_key():",
        "    return uuid.uuid4().hex",
        "",
        "",
    ]
    for t in tools:
        if not t.mutating:
            lines += [
                f"def {t.name}(client, **params):",
                f'    """{t.summary} (read-only, safe to call freely)."""',
                f"    return client.request('{t.method}', '{t.path}', params=params)",
                "", "",
            ]
            continue
        approval_arg = ", approval_token=None" if t.needs_approval else ""
        lines += [
            f"def {t.name}_preview(client, **params):",
            f'    """Preview {t.summary} — shows what WOULD happen, no side effect."""',
            "    return {'action': %r, 'params': params, 'requires_approval': %r}" % (t.name, t.needs_approval),
            "", "",
            f"def {t.name}_commit(client, idempotency_key=None{approval_arg}, **params):",
            f'    """Commit {t.summary}."""',
        ]
        if t.needs_approval:
            lines += [
                "    if not approval_token:",
                f"        raise ApprovalRequired('{t.name} is high-risk and needs an approval token')",
            ]
        lines += [
            "    key = idempotency_key or _idempotency_key()",
            f"    return client.request('{t.method}', '{t.path}', params=params, idempotency_key=key)",
            "", "",
        ]
        if t.undoable:
            lines += [
                f"def {t.name}_undo(client, transaction_id):",
                f'    """Best-effort undo of a prior {t.name}_commit."""',
                "    return client.request('POST', '%s/undo', params={'transaction_id': transaction_id})" % t.path,
                "", "",
            ]
    return "\n".join(lines)


def render_policy_tests(tools: list[SafeTool]) -> str:
    lines = [
        '"""Policy tests for the generated safe tools."""',
        "import pytest",
        "from agent import tools",
        "",
        "",
    ]
    for t in tools:
        if t.mutating and t.needs_approval:
            lines += [
                f"def test_{t.name}_requires_approval():",
                f"    with pytest.raises(tools.ApprovalRequired):",
                f"        tools.{t.name}_commit(client=None)",
                "", "",
            ]
        if t.mutating:
            lines += [
                f"def test_{t.name}_preview_has_no_side_effect():",
                f"    preview = tools.{t.name}_preview(client=None)",
                f"    assert preview['action'] == '{t.name}'",
                "", "",
            ]
    if not any(t.mutating for t in tools):
        lines += ["def test_all_tools_read_only():", "    assert True", ""]
    return "\n".join(lines)


def render_mcp_server(tools: list[SafeTool], name: str = "safe-tools") -> str:
    entries = []
    for t in tools:
        exposed = f"{t.name}_commit" if t.mutating else t.name
        entries.append(f'    {{"name": "{exposed}", "method": "{t.method}", "path": "{t.path}", '
                       f'"high_risk": {str(t.high_risk).lower()}}}')
    joined = ",\n".join(entries)
    return (
        '"""MCP server stub exposing the safe tools. Generated by AgentProof."""\n\n'
        f'SERVER_NAME = "{name}"\n\n'
        "TOOLS = [\n" + joined + "\n]\n\n"
        "# Wire TOOLS into your MCP transport of choice; high_risk tools should be\n"
        "# gated behind a human-approval permission policy.\n"
    )


def compile_to_repo(spec: dict[str, Any], out_dir: str | Path, name: str = "safe-tools") -> list[Path]:
    tools = compile_openapi(spec)
    out = Path(out_dir)
    files = {
        "agent/__init__.py": "",
        "agent/tools.py": render_tools_module(tools),
        "tests/__init__.py": "",
        "tests/test_policy.py": render_policy_tests(tools),
        "mcp_server.py": render_mcp_server(tools, name=name),
        "manifest.json": json.dumps({"name": name, "tools": [t.to_dict() for t in tools]}, indent=2),
    }
    written: list[Path] = []
    for rel, content in files.items():
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
        written.append(p)
    return written
